---
openapi: 3.0.1
info:
  title: Frontend for AWS
  description: Web Frontend for AWS Services
  version: 0.8.18
paths:
  /aws/index.html:
    get:
      responses:
        "200":
          description: Main Page
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/list:
    get:
      parameters:
        - name: resource
          in: query
          schema:
            type: string
            enum:
              - instances
              - reserved
              - spot
              - ami
              - volume
              - snapshot
              - ecr
              - key
              - script
              - user
              - group
              - access-key
              - route53
              - systemd
      responses:
        "200":
          description: List Resources
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/terminate:
    get:
      parameters:
        - name: instance
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Finished
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/create_image:
    get:
      parameters:
        - name: inst_id
          in: query
          schema:
            type: string
        - name: name
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Image ID
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/delete_image:
    get:
      parameters:
        - name: ami
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Finished
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/delete_volume:
    get:
      parameters:
        - name: volid
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Finished
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/modify_volume:
    get:
      parameters:
        - name: volid
          in: query
          schema:
            type: string
        - name: size
          in: query
          schema:
            type: integer
      responses:
        "200":
          description: Finished
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/delete_snapshot:
    get:
      parameters:
        - name: snapid
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Finished
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/create_snapshot:
    get:
      parameters:
        - name: volid
          in: query
          schema:
            type: string
        - name: name
          in: query
          schema:
            nullable: true
            type: string
      responses:
        "200":
          description: Finished
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/tag_item:
    get:
      parameters:
        - name: id
          in: query
          schema:
            type: string
        - name: tag
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Finished
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/delete_ecr_image:
    get:
      parameters:
        - name: reponame
          in: query
          schema:
            type: string
        - name: imageid
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Finished
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/cleanup_ecr_images:
    get:
      responses:
        "200":
          description: Finished
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/edit_script:
    get:
      parameters:
        - name: filename
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Edit Script
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/replace_script:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                filename:
                  type: string
                text:
                  type: string
              type: object
              required:
                - filename
                - text
        required: true
      responses:
        "200":
          description: Finished
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/delete_script:
    get:
      parameters:
        - name: filename
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Finished
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/create_user:
    get:
      parameters:
        - name: user_name
          in: query
          schema:
            type: string
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                properties:
                  arn:
                    type: string
                  create_date:
                    format: datetime
                    type: string
                  user_id:
                    type: string
                  user_name:
                    type: string
                  tags:
                    additionalProperties:
                      type: string
                    type: object
                type: object
                required:
                  - arn
                  - create_date
                  - user_id
                  - user_name
                  - tags
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/delete_user:
    get:
      parameters:
        - name: user_name
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Created Iam User
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/add_user_to_group:
    get:
      parameters:
        - name: user_name
          in: query
          schema:
            type: string
        - name: group_name
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Add User to Group
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/remove_user_from_group:
    get:
      parameters:
        - name: user_name
          in: query
          schema:
            type: string
        - name: group_name
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Remove User to Group
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/create_access_key:
    get:
      parameters:
        - name: user_name
          in: query
          schema:
            type: string
      responses:
        "201":
          description: Create Access Key
          content:
            application/json:
              schema:
                properties:
                  access_key_id:
                    type: string
                  create_date:
                    format: datetime
                    type: string
                  access_key_secret:
                    type: string
                  status:
                    type: string
                  user_name:
                    type: string
                type: object
                required:
                  - access_key_id
                  - create_date
                  - access_key_secret
                  - status
                  - user_name
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/delete_access_key:
    get:
      parameters:
        - name: user_name
          in: query
          schema:
            type: string
        - name: access_key_id
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Delete Access Key
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/build_spot_request:
    get:
      parameters:
        - name: ami
          in: query
          schema:
            nullable: true
            type: string
        - name: inst
          in: query
          schema:
            nullable: true
            type: string
        - name: script
          in: query
          schema:
            nullable: true
            type: string
      responses:
        "200":
          description: Spot Request
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/request_spot:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                ami:
                  type: string
                instance_type:
                  type: string
                security_group:
                  type: string
                script:
                  type: string
                key_name:
                  type: string
                price:
                  type: string
                name:
                  type: string
              type: object
              required:
                - ami
                - instance_type
                - security_group
                - script
                - key_name
                - price
                - name
        required: true
      responses:
        "200":
          description: Finished
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/cancel_spot:
    get:
      parameters:
        - name: spot_id
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Cancelled Spot
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/prices:
    get:
      parameters:
        - name: search
          in: query
          schema:
            nullable: true
            type: string
      responses:
        "200":
          description: Prices
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/update:
    get:
      responses:
        "200":
          description: Update
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/instance_status:
    get:
      parameters:
        - name: instance
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Instance Status
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/command:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                instance:
                  type: string
                command:
                  type: string
              type: object
              required:
                - instance
                - command
        required: true
      responses:
        "200":
          description: Run Command on Instance
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/instances:
    get:
      parameters:
        - name: inst
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Describe Instances
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/user:
    get:
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                properties:
                  email:
                    type: string
                type: object
                required:
                  - email
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/novnc/start:
    get:
      responses:
        "200":
          description: Start NoVNC
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/novnc/status:
    get:
      responses:
        "200":
          description: NoVNC Status
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/novnc/stop:
    get:
      responses:
        "200":
          description: Stop NoVNC
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/update_dns_name:
    get:
      parameters:
        - name: zone
          in: query
          schema:
            type: string
        - name: dns_name
          in: query
          schema:
            type: string
        - name: old_ip
          in: query
          schema:
            format: ipv4_address
            type: string
        - name: new_ip
          in: query
          schema:
            format: ipv4_address
            type: string
      responses:
        "201":
          description: Update Dns
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/systemd_action:
    get:
      parameters:
        - name: action
          in: query
          schema:
            type: string
            enum:
              - start
              - stop
              - restart
        - name: service
          in: query
          schema:
            type: string
      responses:
        "201":
          description: Update Dns
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  "/aws/systemd_logs/{service}":
    get:
      parameters:
        - name: service
          in: path
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Systemd Logs
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /aws/systemd_restart_all:
    get:
      responses:
        "201":
          description: Systemd Restart All
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  "/aws/crontab_logs/{crontab_type}":
    get:
      parameters:
        - name: crontab_type
          in: path
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Crontab Logs
          content:
            text/html:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
